version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - ./zookeeper:/opt/zookeeper-3.4.13/data

  kafka1:
    image: wurstmeister/kafka
    ports:
      - 9192:9192
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9192
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka1:9092,OUTSIDE://kafka1:9192
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_LOG_DIRS=/kafka/kafka-logs
    volumes:
      - ./kafka/kafka-logs1:/kafka/kafka-logs

  kafka2:
    image: wurstmeister/kafka
    ports:
      - 9292:9292
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9292
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka2:9092,OUTSIDE://kafka2:9292
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_LOG_DIRS=/kafka/kafka-logs
    volumes:
      - ./kafka/kafka-logs2:/kafka/kafka-logs

  kafka3:
    image: wurstmeister/kafka
    ports:
      - 9392:9392
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9392
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka3:9092,OUTSIDE://kafka3:9392
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_LOG_DIRS=/kafka/kafka-logs
    volumes:
      - ./kafka/kafka-logs3:/kafka/kafka-logs

  kafka-manager:
    build: ./kafka-manager
    ports:
      - 9000:9000
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper
    environment:
      - ZK_HOSTS=zookeeper:2181

  sourcedb:
    build: ./sourcedb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  targetdb1:
    build: ./targetdb1
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  targetdb2:
    build: ./targetdb2
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  nifi:
    image: apache/nifi:latest
    ports:
      - 9090:9090
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper
      - sourcedb
      - targetdb1
      - targetdb2
    environment:
      NIFI_WEB_HTTP_PORT: 9090
    volumes:
      - ./nifi:/nifi

  prometheus:
    image: prom/prometheus
    ports:
      - "9080:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/usr/share/grafana/conf/provisioning

  kafka-worker:
    build: ./kafka-worker
    command: bash -c "sleep infinity"
    volumes:
      - ./kafka-script:/kafka-script
