version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://:9093,OUTSIDE://:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE

  kafka-manager:
    image: kafka-manager
    ports:
      - 9000:9000
    depends_on:
      - kafka
      - zookeeper
    environment:
      - ZK_HOSTS=zookeeper:2181

  sourcedb:
    build: ./sourcedb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  targetdb1:
    build: ./targetdb1
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  targetdb2:
    build: ./targetdb2
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  nifi:
    image: apache/nifi:latest
    ports:
      - 9090:9090
    depends_on:
      - kafka
      - zookeeper
      - sourcedb
      - targetdb1
      - targetdb2
    environment:
      NIFI_WEB_HTTP_PORT: 9090
    volumes:
      - ./nifi:/nifi

  prometheus:
    image: prom/prometheus
    ports:
      - "9080:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/usr/share/grafana/conf/provisioning
